spring:
  cloud:
    gateway:
      mvc:
        routes:
          - id: customer-service
            uri: lb://CUSTOMER-SERVICE
            predicates:
              - Path=/api/customers/**
          - id: inventory-service
            uri: lb://INVENTORY-SERVICE
            predicates:
              - Path=/api/products/**
          - id: billing-service
            uri: lb://BILLING-SERVICE
            predicates:
              - Path=/api/bills/**

eureka:
  client:
    service-url:
      defaultZone: http://eureka-discovery:8761/eureka
  instance:
    prefer-ip-address: true
    hostname: gateway-service

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway
